config/routes.rb
Rails.application.routes.draw do
  root to: "imports#index"
  resources :imports do
    collection do
      get 'etl_process'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/import.rb
# coding: utf-8
# frozen_string_literal: true
class Import < ApplicationRecord
end

app/models/unit.rb
# coding: utf-8
# frozen_string_literal: true

require 'etl'

 # price       | numeric(8,2)
 # name        | character varying
 # description | text
 # area        | double precision
 # uom         | character varying

class Unit < ApplicationRecord

  validates :name, presence: true

  # returns boolean
  def self.process_imports
    attributes = {connection: ActiveRecord::Base.connection}
    result = Etl::Job.new(attributes).run
    update_column(:done, true) if result
    result
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :set_import, only: [:show, :update, :destroy]

  # GET /imports
  def index
    @units = Unit.all
  end

  # POST /imports
  # POST /imports.json
  def create
    #return render html: import_params["files"].original_filename.inspect
    full_params = import_params.merge(file: import_params["files"].original_filename)
    @import = Import.new(full_params)

    respond_to do |format|
      if @import.save
        format.html { redirect_to imports_path, notice: 'Import was successfully created.' }
        format.json { render :show, status: :created, location: @import }
      else
        format.html { redirect_to imports_path, notice: 'Something went wrong.' }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /imports/process
  def etl_process
    if Unit.process_imports
      redirect_to imports_path, notice: 'File was successfully imported.'
    else
      return render html: 'Something went wrong with the file.'
    end
  end

  # PATCH/PUT /imports/1
  # PATCH/PUT /imports/1.json
  def update
    respond_to do |format|
      if @import.update(import_params)
        format.html { redirect_to @import, notice: 'Import was successfully updated.' }
        format.json { render :show, status: :ok, location: @import }
      else
        format.html { render :edit }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imports/1
  # DELETE /imports/1.json
  def destroy
    @import.destroy
    respond_to do |format|
      format.html { redirect_to imports_url, notice: 'Import was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_import
      @import = Import.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def import_params
      params.require(:import).permit(:notes, :sumcheck, :file, :files)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/imports/_form.html.haml
= form_for @image do |f|
  - if @image.errors.any?
    #error_explanation
      %h2= "#{pluralize(@image.errors.count, "error")} prohibited this image from being saved:"
      %ul
        - @image.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :file
    = f.text_area :file
  .field
    = f.label :active
    = f.check_box :active
  .actions
    = f.submit 'Save'

app/views/imports/edit.html.haml
%h1 Editing image

= render 'form'

= link_to 'Show', @image
\|
= link_to 'Back', images_path

app/views/imports/index.html.haml
%h1 Unit Files

= button_to "Import Files", etl_process_imports_path, method: :get

%table
  %thead
    %tr
      %th Price
      %th Name
      %th Description
      %th Area

  %tbody
    - @units.each do |unit|
      %tr
        %td= unit.price
        %td= unit.name
        %td= unit.description
        %td= unit.area

%br

app/views/imports/new.html.haml
%h1 New import

= render 'form'

= link_to 'Back', imports_path

app/views/imports/show.html.haml
%p#notice= notice

%p
  %b User:
  = @image.user
%p
  %b File:
  = @image.file
%p
  %b Active:
  = @image.active

= link_to 'Edit', edit_image_path(@image)
\|
= link_to 'Back', images_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>:: Etl Starter App::</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>